/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package template.main.containers;

import classes.Editora;
import classes.Obra;
import java.util.List;
import services.*;

/**
 *
 * @author nafta
 */
public class EditObra extends javax.swing.JFrame {

    /**
     * Creates new form addworker
     */
    EditoraService service=new EditoraService();
    public EditObra() {
        initComponents();
        setResizable(false);
        Editoras();

    }
 void Editoras(){
        try{
          List<Editora> list ;
            list = service.readAll();
            for(Editora e: list){
            cb_editora.addItem(e.getNome());
            }
        }catch(Exception ex){}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param id
     */
    @SuppressWarnings("unchecked")
         
        public void starter(int id){
        try {
        ObraService os = new ObraService();
        Obra o= new Obra();
        o=os.read(id);
        tf_titulo.setText(o.getTitulo());
        tf_isbn.setText(o.getIsbn());
        tf_edicao.setText(o.getEdicao());
        tf_ano.setText(o.getAno().toString());
        tf_sinopse.setText(o.getSinopse());
        cb_editora.setSelectedItem(service.read(o.getEditoraId()).getNome());
        cb_idioma.setSelectedItem(o.getIdioma());
        lb_id.setText(String.valueOf(id));
       
        } catch (Exception ex) {
            System.getLogger(EditObra.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        tf_ano = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lb_ = new javax.swing.JLabel();
        tf_isbn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_edicao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_sinopse = new javax.swing.JTextField();
        cb_editora = new javax.swing.JComboBox<>();
        tf_titulo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        cb_idioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tf_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_anoActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo");

        jLabel7.setText("Isbn");

        lb_.setText("Edição");

        jLabel8.setText("Ano");

        jLabel9.setText("Editora");

        jLabel10.setText("Idioma");

        jLabel11.setText("Sinopse");

        lb_id.setText("jLabel2");
        lb_id.setEnabled(false);

        cb_idioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inglês", "Português", "Espanhol", "Francês", "Alemão", "Italiano", "Holandês", "Sueco", "Norueguês", "Dinamarquês", "Finlandês", "Russo", "Ucraniano", "Polaco", "Checo", "Eslovaco", "Húngaro", "Romeno", "Búlgaro", "Sérvio", "Croata", "Bósnio", "Macedónio", "Albanês", "Grego", "Turco", "Árabe", "Hebraico", "Persa (Farsi)", "Urdu", "Hindi", "Bengali", "Punjabi", "Nepalês", "Tibetano", "Chinês Mandarim", "Cantonês", "Japonês", "Coreano", "Vietnamita", "Tailandês", "Indonésio", "Malaio", "Filipino (Tagalog)", "Suaíli", "Zulu", "Amárico", "Yoruba", "Lingala", "Kimbundo" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addComponent(lb_id)
                .addGap(91, 91, 91)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(cb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lb_, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_edicao, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(tf_titulo)
                        .addComponent(cb_editora, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(213, 213, 213))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_sinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(26, 26, 26)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(cb_idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lb_id))
                .addGap(15, 15, 15))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(tf_isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(lb_)
                        .addComponent(tf_ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_sinopse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addContainerGap(24, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(593, 255));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
        ObraService os = new ObraService();
        Obra o = new Obra();
        o.setTitulo(tf_titulo.getText());
        o.setEdicao(tf_edicao.getText());
        o.setIsbn(tf_isbn.getText());
        o.setAno(Integer.valueOf(tf_ano.getText()));
        o.setEditoraId(service.readByName(cb_editora.getSelectedItem().toString()));
        o.setIdioma(cb_idioma.getSelectedItem().toString());
        o.setSinopse(tf_sinopse.getText());
        o.setId(Long.parseLong(lb_id.getText()));
   
            os.update(o);
            GutilizadorPanel gs = new GutilizadorPanel();
            gs.fillTable(null);
            this.dispose();

        } catch (Exception ex) {
            System.getLogger(EditObra.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_anoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_anoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new EditObra().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_editora;
    private javax.swing.JComboBox<String> cb_idioma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_;
    private javax.swing.JLabel lb_id;
    private javax.swing.JTextField tf_ano;
    private javax.swing.JTextField tf_edicao;
    private javax.swing.JTextField tf_isbn;
    private javax.swing.JTextField tf_sinopse;
    private javax.swing.JTextField tf_titulo;
    // End of variables declaration//GEN-END:variables
}
