/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package template.main.containers;

import classes.*;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import services.*;
import template.main.layout;

/**
 *
 * @author nafta
 */
public class EditEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form addworker
     */
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    ObraService obra = new ObraService();
    UtilizadorService user = new UtilizadorService();
    ExemplarService exes = new ExemplarService();

    public EditEmprestimo() {
        initComponents();
        setResizable(false);
        exes();
        users();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *
     * @param id
     */
    @SuppressWarnings("unchecked")

    void exes() {
        try {
            List<Exemplar> list;
            list = exes.readAll();
            for (Exemplar e : list) {
                cb_exe.addItem(obra.read(e.getObraId()).getTitulo());
            }
        } catch (Exception ex) {
        }
    }

    void users() {
        try {
            List<Utilizador> list;
            list = user.readAll();
            for (Utilizador u : list) {
                cb_user.addItem(u.getNomeCompleto());
            }
        } catch (Exception ex) {
        }
    }

    public void starter(int id) {
        try {
            EmprestimoService es = new EmprestimoService();
            Emprestimo e = new Emprestimo();
            e = es.read(id);
            lb_id.setText(String.valueOf(id));
            tf_data.setText(sdf.format(e.getDataEmprestimo()));
            tf_dataPrev.setText(sdf.format(e.getDataPrevistaDevolucao()));
            tf_dataDev.setText(sdf.format(e.getDataDevolucao()));
            cb_exe.setSelectedItem(obra.readByExemplar(e.getExemplarId()));
            cb_user.setSelectedItem(user.read(e.getUtilizadorId()).getNomeCompleto());
            cb_estado.setSelectedItem(e.getEstado());

        } catch (Exception e) {
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        tf_data = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_exe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_estado = new javax.swing.JComboBox<>();
        cb_user = new javax.swing.JComboBox<>();
        lb_user = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_dataPrev = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_dataDev = new javax.swing.JFormattedTextField();
        lb_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Data");

        jLabel1.setText("Obra");

        jLabel2.setText("Estado");

        cb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABERTO", "DEVOLVIDO", "ATRASADO" }));

        lb_user.setText("Usuario");

        jLabel8.setText("Data Prev");

        jLabel9.setText("Data Dev");

        lb_id.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lb_user, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cb_estado, 0, 207, Short.MAX_VALUE)
                            .addComponent(cb_exe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_user, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lb_id)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(184, 184, 184)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tf_data, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dataPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_dataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(cb_exe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_user)
                    .addComponent(jLabel8)
                    .addComponent(tf_dataPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_dataDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lb_id))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(593, 218));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {

            Emprestimo e = new Emprestimo();
            String nomeExemplar = cb_exe.getSelectedItem().toString();
            Long exemplarId = exes.readByObra(obra.readByNome(nomeExemplar));
            e.setExemplarId(exemplarId);
            java.util.Date utilDataEmprestimo = sdf.parse(tf_data.getText().trim());
            java.util.Date utilDataPrevista = sdf.parse(tf_dataPrev.getText().trim());
            java.util.Date utilDataDev = sdf.parse(tf_dataDev.getText().trim());
            java.sql.Date sqlDataEmprestimo = new java.sql.Date(utilDataEmprestimo.getTime());
            java.sql.Date sqlDataPrevista = new java.sql.Date(utilDataPrevista.getTime());
            java.sql.Date sqlDataDev = new java.sql.Date(utilDataDev.getTime());
            e.setDataEmprestimo(sqlDataEmprestimo);
            e.setDataPrevistaDevolucao(sqlDataPrevista);
            e.setDataDevolucao(sqlDataDev);
            if (cb_user.getSelectedItem() != null) {
                String nomeUser = cb_user.getSelectedItem().toString();
                e.setUtilizadorId(user.readByNome(nomeUser));
            } else {
                e.setUtilizadorId(layout.idUser);
            }
            e.setId(Long.valueOf(lb_id.getText()));
            e.setEstado(cb_estado.getSelectedItem().toString());
            EmprestimoService es = new EmprestimoService();
            es.update(e);
            if (cb_estado.getSelectedItem().toString() == "ATRASADO") {
                MultaService ms = new MultaService();
                ms.processarMulta(e);
            }

            GcirculacaoPanel gc = new GcirculacaoPanel();
            //  gc.fillTable(null);
            this.dispose();

        } catch (Exception ex) {
            System.getLogger(EditEmprestimo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditEmprestimo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_estado;
    private javax.swing.JComboBox<String> cb_exe;
    public javax.swing.JComboBox<String> cb_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_id;
    public javax.swing.JLabel lb_user;
    private javax.swing.JFormattedTextField tf_data;
    private javax.swing.JFormattedTextField tf_dataDev;
    private javax.swing.JFormattedTextField tf_dataPrev;
    // End of variables declaration//GEN-END:variables
}
