/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package template.main.containers;

import classes.Editora;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.EditoraService;

/**
 *
 * @author naftalipinto
 */
public final class GeditoraPanel extends javax.swing.JPanel {

    /**
     * Creates new form GutilizadorPanel
     */
    public GeditoraPanel() {
        initComponents();
        initializeTable();
        fillTable(null);
    }

    void fillTable(String filter) {
        try {
            EditoraService service = new EditoraService();
            List<Editora> list = null;
            list = service.readAll();

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);  // Limpa apenas as linhas, mantém as colunas

            // Converte o filtro para minúsculas uma única vez
            String lowerFilter = (filter == null || filter.trim().isEmpty())
                    ? null : filter.toLowerCase();

            for (Editora e : list) {
                // Se oranão há filtro ou se algum campo corresponde ao filtro
                if (lowerFilter == null
                        || e.getNome().toLowerCase().contains(lowerFilter)
                        || e.getTelefone().toLowerCase().contains(lowerFilter)
                        || e.getEmail().toLowerCase().contains(lowerFilter)
                        || e.getEndereco().toLowerCase().contains(lowerFilter)) {

                    addRowToModel(model, e);
                }
            }
        } catch (Exception ex) {
        }
    }

    private void addRowToModel(DefaultTableModel model, Editora e) {
        try {
            model.addRow(new Object[]{
                e.getId(), // Coluna 0 - ID
                e.getNome(), // Coluna 1 - Nome
                e.getEmail(), // Coluna 2 - BI
                e.getTelefone(), // Coluna 3 - Data Nasc
                e.getEndereco()
            });
        } catch (Exception ex) {
        }
    }

    public void initializeTable() {
        try {
            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    // Defina os tipos de cada coluna conforme necessário
                    if (columnIndex == 0) {
                        return Integer.class; // ID
                    }
                    return String.class;
                }
            };

            // Defina as colunas na ordem CORRETA que corresponda à sua classe worker
            model.setColumnIdentifiers(new String[]{
                "ID", // 0
                "Nome", // 1
                "Email", // 2
                "Telefone", // 3
                "Morada"
            });

            table.setModel(model);
            table.getColumnModel().getColumn(0).setMinWidth(0);
            table.getColumnModel().getColumn(0).setMaxWidth(0);
            table.getColumnModel().getColumn(0).setWidth(0);
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tf_pesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone", "Endereco"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        tf_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_pesquisarKeyTyped(evt);
            }
        });

        jButton1.setText("Adicionar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            addEditora add = new addEditora();
            add.setVisible(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            int selectedRow = table.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Selecione uma editora  primeiro!");
                return;
            }
            long id = (long) model.getValueAt(selectedRow, 0); // <-- CORRETO
            EditEditora e = new EditEditora();
            e.starter((int) id);
            e.setVisible(true);

        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_tableMouseClicked

    private void tf_pesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pesquisarKeyTyped
        // TODO add your handling code here:
        fillTable(tf_pesquisar.getText());
    }//GEN-LAST:event_tf_pesquisarKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf_pesquisar;
    // End of variables declaration//GEN-END:variables
}
