/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package template.main.containers;

import classes.Obra;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.*;

/**
 *
 * @author naftalipinto
 */
public class GobraPanel extends javax.swing.JPanel {

    /**
     * Creates new form GutilizadorPanel
     */
    EditoraService editora = new EditoraService();

    public GobraPanel() {
        initComponents();
        initializeTable();
        fillTable(null);
    }

    public void fillTable(String filter) {
        try {
            ObraService service = new ObraService();
            List<Obra> list = null;
            list = service.readAll();
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0);  // Limpa apenas as linhas, mantém as colunas
            // Converte o filtro para minúsculas uma única vez
            String lowerFilter = (filter == null || filter.trim().isEmpty())
                    ? null : filter.toLowerCase();

            for (Obra o : list) {
                // Se não há filtro ou se algum campo corresponde ao filtro
                if (lowerFilter == null
                        || o.getTitulo().toLowerCase().contains(lowerFilter)
                        || o.getEdicao().toLowerCase().contains(lowerFilter)
                        || o.getIdioma().toLowerCase().contains(lowerFilter)
                        || o.getSinopse().toLowerCase().contains(lowerFilter)) {

                    addRowToModel(model, o);
                }
            }
        } catch (Exception ex) {
        }
    }

    private void addRowToModel(DefaultTableModel model, Obra o) {
        try {
            model.addRow(new Object[]{
                o.getId(),
                o.getTitulo(),
                o.getIsbn(),
                o.getAno(),
                o.getEdicao(),
                o.getIdioma(),
                editora.read(o.getEditoraId()).getNome(),
                o.getSinopse()
            });
        } catch (Exception ex) {
        }
    }

    private void initializeTable() {
        try {
            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public Class<?> getColumnClass(int columnIndex) {
                    // Defina os tipos de cada coluna conforme necessário
                    if (columnIndex == 0) {
                        return Integer.class; // ID
                    }
                    return String.class;
                }
            };

            // Defina as colunas na ordem CORRETA que corresponda à sua classe worker
            model.setColumnIdentifiers(new String[]{
                "ID", // 0
                "titulo", // 1
                "Isbn", // 2
                "Ano", // 3
                "Edição", // 4
                "Edioma", // 5
                "Sinopse", // 5
                "Editora"
            });

            table.setModel(model);
            table.getColumnModel().getColumn(0).setMinWidth(0);
            table.getColumnModel().getColumn(0).setMaxWidth(0);
            table.getColumnModel().getColumn(0).setWidth(0);
        } catch (Exception ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tf_pesquisar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "ISBN", "Ano Lançamento", "Edição", "Idiioma", "Editora", "Sipnose"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            addObra add = new addObra();
            add.setVisible(true);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            int selectedRow = table.getSelectedRow();

            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um utilizador primeiro!");
                return;
            }

            DefaultTableModel model = (DefaultTableModel) table.getModel();

            long id = (long) model.getValueAt(selectedRow, 0); // <-- CORRETO

            EditObra o = new EditObra();
            o.starter((int) id);
            o.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField tf_pesquisar;
    // End of variables declaration//GEN-END:variables
}
