/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package template.main.containers;

import classes.Database;
import javax.swing.JOptionPane;
import com.itextpdf.text.Document;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;

// Para tabelas (PdfPTable)
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfWriter;

// Para linha separadora (opcional)
import com.itextpdf.text.pdf.draw.LineSeparator;
import java.awt.Desktop;

// Imports Java padrão
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author naftalipinto
 */
public final class relatorio extends javax.swing.JPanel {

    /**
     * Creates new form GutilizadorPanel
     */
    public relatorio() {
        initComponents();
       
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1047, 707));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setText("Gerar Relatorio");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(405, 405, 405)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(303, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void gerarRelatorioPDFCompleto() {
    Document doc = new Document(PageSize.A4.rotate()); // Paisagem para mais colunas
    doc.setMargins(20, 20, 20, 20);
    
    try {
        // Criar PDF
        PdfWriter.getInstance(doc, new FileOutputStream("Relatorio_SGBU_Completo.pdf"));
        doc.open();
        
        // Conexão com banco
        Connection con = Database.getConnection();
        
        // ========== CABEÇALHO ==========
        Font tituloFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD, BaseColor.DARK_GRAY);
        Paragraph titulo = new Paragraph("RELATÓRIO COMPLETO - SISTEMA SGBU", tituloFont);
        titulo.setAlignment(Element.ALIGN_CENTER);
        titulo.setSpacingAfter(10);
        doc.add(titulo);
        
        Font subtituloFont = new Font(Font.FontFamily.HELVETICA, 12, Font.NORMAL, BaseColor.GRAY);
        Paragraph subtitulo = new Paragraph("Gerado em: " + new SimpleDateFormat("dd/MM/yyyy HH:mm").format(new Date()), subtituloFont);
        subtitulo.setAlignment(Element.ALIGN_CENTER);
        subtitulo.setSpacingAfter(20);
        doc.add(subtitulo);
        
        doc.add(new Chunk("\n"));
        doc.add(new LineSeparator());
        doc.add(new Chunk("\n"));
        
        // ========== RESUMO ESTATÍSTICO ==========
        adicionarResumoEstatistico(doc, con);
        
        // ========== TABELA DE UTILIZADORES ==========
        adicionarTabela(doc, con, "UTILIZADORES", 
            "SELECT nomeCompleto, email, perfil, estado, " +
            "DATE_FORMAT(dataRegisto, '%d/%m/%Y') as dataReg " +
            "FROM Utilizador ORDER BY perfil, nomeCompleto",
            new String[]{"Nome", "Email", "Perfil", "Estado", "Data Registo"},
            new float[]{3f, 3f, 1.5f, 1.5f, 1.5f}
        );
        
        // ========== TABELA DE EDITORAS ==========
        // CORREÇÃO: Mudou Morada para Endereço e removeu dataRegisto
        adicionarTabela(doc, con, "EDITORAS CADASTRADAS",
            "SELECT nome, endereco, telefone, email " +  // Removido: , DATE_FORMAT(dataRegisto, '%d/%m/%Y') as dataRegistro
            "FROM Editora ORDER BY nome",
            new String[]{"Nome", "Endereço", "Telefone", "Email"}, // Morada → Endereço
            new float[]{2f, 3f, 1.5f, 2f} // Ajustado larguras
        );
        
        // ========== TABELA DE OBRAS ==========
        adicionarTabela(doc, con, "CATÁLOGO DE OBRAS",
            "SELECT titulo, isbn, ano, edicao, idioma, " +
            "(SELECT COUNT(*) FROM Exemplar e WHERE e.obraId = o.id) as totalExemplares " +
            "FROM Obra o ORDER BY titulo",
            new String[]{"Título", "ISBN", "Ano", "Edição", "Idioma", "Exemplares"},
            new float[]{4f, 2f, 0.8f, 1.2f, 1f, 1f}
        );
        
        // ========== TABELA DE EXEMPLARES ==========
        adicionarTabela(doc, con, "EXEMPLARES - ESTADO ATUAL",
            "SELECT e.codigoBarras, e.cota, e.estado, o.titulo, " +
            "DATE_FORMAT(FROM_UNIXTIME(e.aquisicaoData/1000), '%d/%m/%Y') as dataAquisicao " +
            "FROM Exemplar e " +
            "JOIN Obra o ON e.obraId = o.id " +
            "ORDER BY e.estado, e.codigoBarras",
            new String[]{"Código Barras", "Cota", "Estado", "Obra", "Aquisição"},
            new float[]{1.5f, 1.5f, 1.2f, 3f, 1.3f}
        );
        
        // ========== TABELA DE EMPRÉSTIMOS ATIVOS ==========
        adicionarTabela(doc, con, "EMPRÉSTIMOS",
            "SELECT u.nomeCompleto, o.titulo, ex.codigoBarras, " +
            "DATE_FORMAT(FROM_UNIXTIME(e.dataEmprestimo/1000), '%d/%m/%Y') as dataEmp, " +
            "DATE_FORMAT(FROM_UNIXTIME(e.dataPrevistaDevolucao/1000), '%d/%m/%Y') as dataPrev " +
            "FROM Emprestimo e " +
            "JOIN Utilizador u ON e.utilizadorId = u.id " +
            "JOIN Exemplar ex ON e.exemplarId = ex.id " +
            "JOIN Obra o ON ex.obraId = o.id " +
            "WHERE e.estado = 'ABERTO' " +
            "ORDER BY e.dataPrevistaDevolucao",
            new String[]{"Utilizador", "Obra", "Código", "Data Emp", "Data Prev"},
            new float[]{2.5f, 3f, 1.5f, 1.5f, 1.5f}
        );
        
        // ========== TABELA DE RESERVAS ==========
        adicionarTabela(doc, con, "RESERVAS",
            "SELECT u.nomeCompleto, o.titulo, r.posicaoFila, " +
            "DATE_FORMAT(FROM_UNIXTIME(r.dataReserva/1000), '%d/%m/%Y') as dataReserva " +
            "FROM Reserva r " +
            "JOIN Utilizador u ON r.utilizadorId = u.id " +
            "JOIN Obra o ON r.obraId = o.id " +
            "WHERE r.status = 'ATIVA' " +
            "ORDER BY r.posicaoFila",
            new String[]{"Utilizador", "Obra", "Posição", "Data Reserva"},
            new float[]{3f, 3f, 1f, 1.5f}
        );
        
        // ========== TABELA DE MULTAS EM ABERTO ==========
        adicionarTabelaComTotal(doc, con, "MULTAS EM ABERTO",
            "SELECT u.nomeCompleto, m.valor, m.motivo, o.titulo, " +
            "DATE_FORMAT(FROM_UNIXTIME(m.dataGeracao/1000), '%d/%m/%Y') as dataGeracao " +
            "FROM Multa m " +
            "JOIN Emprestimo e ON m.emprestimoId = e.id " +
            "JOIN Exemplar ex ON e.exemplarId = ex.id " +
            "JOIN Obra o ON ex.obraId = o.id " +
            "JOIN Utilizador u ON e.utilizadorId = u.id " +
            "WHERE m.pago = false " +
            "ORDER BY m.valor DESC",
            new String[]{"Utilizador", "Valor (Kz)", "Motivo", "Obra", "Data Geração"},
            new float[]{2.5f, 1.5f, 1.5f, 2.5f, 1.5f},
            "valor" // Coluna para somar
        );
        
        // ========== RODAPÉ ==========
        doc.add(new Chunk("\n\n"));
        doc.add(new LineSeparator());
        
        Font rodapeFont = new Font(Font.FontFamily.HELVETICA, 9, Font.ITALIC, BaseColor.GRAY);
        Paragraph rodape = new Paragraph(
            "Relatório gerado automaticamente pelo Sistema de Gestão de Biblioteca Universitária (SGBU)\n",
            rodapeFont
        );
        rodape.setAlignment(Element.ALIGN_CENTER);
        doc.add(rodape);
        
        // Fechar conexão
        con.close();
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, 
            "Erro ao gerar relatório: " + e.getMessage(), 
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
    } finally {
        doc.close();
    }
    
    // Abrir PDF automaticamente
    try {
        Desktop.getDesktop().open(new File("Relatorio_SGBU_Completo.pdf"));
    } catch (Exception e) {
        e.printStackTrace();
    }
}

// ========== MÉTODOS AUXILIARES ==========

private void adicionarResumoEstatistico(Document doc, Connection con) throws Exception {
    Font sectionFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, BaseColor.BLUE);
    Paragraph section = new Paragraph("RESUMO ESTATÍSTICO", sectionFont);
    section.setSpacingAfter(10);
    doc.add(section);
    
    // Obter estatísticas
    int[] estatisticas = obterEstatisticas(con);
    
    PdfPTable table = new PdfPTable(2);
    table.setWidthPercentage(100);
    table.setSpacingBefore(10);
    table.setSpacingAfter(20);
    
    // Cabeçalho
    Font headerFont = new Font(Font.FontFamily.HELVETICA, 11, Font.BOLD, BaseColor.WHITE);
    PdfPCell headerCell = new PdfPCell(new Phrase("ESTATÍSTICA", headerFont));
    headerCell.setBackgroundColor(BaseColor.DARK_GRAY);
    headerCell.setHorizontalAlignment(Element.ALIGN_CENTER);
    headerCell.setPadding(8);
    table.addCell(headerCell);
    
    headerCell = new PdfPCell(new Phrase("VALOR", headerFont));
    headerCell.setBackgroundColor(BaseColor.DARK_GRAY);
    headerCell.setHorizontalAlignment(Element.ALIGN_CENTER);
    headerCell.setPadding(8);
    table.addCell(headerCell);
    
    // Dados - AGORA COM 7 ITENS
    Font dataFont = new Font(Font.FontFamily.HELVETICA, 10);
    String[] labels = {
        "Total de Utilizadores",
        "Total de Editoras",
        "Total de Obras", 
        "Total de Exemplares",
        "Empréstimos Ativos",
        "Reservas Ativas",
        "Multas em Aberto (Kz)"  // ← AGORA SÃO 7 ITENS
    };
    
    for (int i = 0; i < labels.length; i++) {
        PdfPCell labelCell = new PdfPCell(new Phrase(labels[i], dataFont));
        labelCell.setPadding(5);
        table.addCell(labelCell);
        
        String value;
        if (i == 6) { // Multas (agora posição 6)
            value = String.format("%,.2f", (double) estatisticas[i]);
        } else {
            value = String.valueOf(estatisticas[i]);
        }
        
        PdfPCell valueCell = new PdfPCell(new Phrase(value, dataFont));
        valueCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        valueCell.setPadding(5);
        table.addCell(valueCell);
    }
    
    doc.add(table);
}

private int[] obterEstatisticas(Connection con) throws SQLException {
    // CORREÇÃO: Agora array com tamanho 7
    int[] stats = new int[7]; // Índices: 0,1,2,3,4,5,6
    
    String[] queries = {
        "SELECT COUNT(*) FROM Utilizador",
        "SELECT COUNT(*) FROM Editora",
        "SELECT COUNT(*) FROM Obra",
        "SELECT COUNT(*) FROM Exemplar",
        "SELECT COUNT(*) FROM Emprestimo WHERE estado = 'ABERTO'",
        "SELECT COUNT(*) FROM Reserva WHERE status = 'ATIVA'",
        "SELECT COALESCE(SUM(valor), 0) FROM Multa WHERE pago = false"
    };
    
    Statement stmt = con.createStatement();
    for (int i = 0; i < queries.length; i++) {
        ResultSet rs = stmt.executeQuery(queries[i]);
        if (rs.next()) {
            // CORREÇÃO: Cast para double apenas na última query
            stats[i] = i == 6 ? (int) rs.getDouble(1) : rs.getInt(1);
        }
        rs.close();
    }
    stmt.close();
    
    return stats;
}



private void adicionarTabela(Document doc, Connection con, String titulo, 
                            String sql, String[] colunas, float[] larguras) throws Exception {
    
    // Título da seção
    Font sectionFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, BaseColor.BLUE);
    Paragraph section = new Paragraph(titulo, sectionFont);
    section.setSpacingBefore(20);
    section.setSpacingAfter(10);
    doc.add(section);
    
    // Criar tabela
    PdfPTable table = new PdfPTable(colunas.length);
    table.setWidthPercentage(100);
    if (larguras != null) {
        table.setWidths(larguras);
    }
    
    // Cabeçalho
    Font headerFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
    for (String coluna : colunas) {
        PdfPCell cell = new PdfPCell(new Phrase(coluna, headerFont));
        cell.setBackgroundColor(BaseColor.DARK_GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(5);
        table.addCell(cell);
    }
    
    // Dados
    Font dataFont = new Font(Font.FontFamily.HELVETICA, 9);
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery(sql);
    
    int rowCount = 0;
    while (rs.next() && rowCount < 100) { // Limita a 100 linhas por tabela
        for (int i = 1; i <= colunas.length; i++) {
            String valor = rs.getString(i);
            if (valor == null) valor = "-";
            
            PdfPCell cell = new PdfPCell(new Phrase(valor, dataFont));
            cell.setPadding(4);
            
            // Colorir células especiais
            if (colunas[i-1].equals("Estado")) {
                cell.setBackgroundColor(corPorEstado(valor));
            } else if (colunas[i-1].equals("Perfil")) {
                cell.setBackgroundColor(corPorPerfil(valor));
            }
            
            table.addCell(cell);
        }
        rowCount++;
    }
    
    if (rowCount == 0) {
        PdfPCell emptyCell = new PdfPCell(new Phrase("Nenhum registro encontrado", dataFont));
        emptyCell.setColspan(colunas.length);
        emptyCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(emptyCell);
    }
    
    rs.close();
    stmt.close();
    doc.add(table);
    
    // Nota se atingiu limite
    if (rowCount >= 100) {
        Font notaFont = new Font(Font.FontFamily.HELVETICA, 8, Font.ITALIC, BaseColor.GRAY);
        Paragraph nota = new Paragraph("* Mostrando apenas os primeiros 100 registros", notaFont);
        doc.add(nota);
    }
}

private void adicionarTabelaComTotal(Document doc, Connection con, String titulo,
                                    String sql, String[] colunas, float[] larguras,
                                    String colunaSoma) throws Exception {
    
    // Primeiro obtém os dados e calcula total
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery(sql.replace("SELECT", "SELECT SQL_CALC_FOUND_ROWS"));
    
    double total = 0;
    int rowCount = 0;
    
    // Contar linhas e calcular total
    Statement stmtCount = con.createStatement();
    ResultSet rsCount = stmtCount.executeQuery("SELECT FOUND_ROWS()");
    if (rsCount.next()) {
        rowCount = rsCount.getInt(1);
    }
    rsCount.close();
    stmtCount.close();
    
    // Título da seção
    Font sectionFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, BaseColor.BLUE);
    Paragraph section = new Paragraph(titulo, sectionFont);
    section.setSpacingBefore(20);
    section.setSpacingAfter(10);
    doc.add(section);
    
    // Criar tabela
    PdfPTable table = new PdfPTable(colunas.length);
    table.setWidthPercentage(100);
    if (larguras != null) {
        table.setWidths(larguras);
    }
    
    // Cabeçalho
    Font headerFont = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
    for (String coluna : colunas) {
        PdfPCell cell = new PdfPCell(new Phrase(coluna, headerFont));
        cell.setBackgroundColor(BaseColor.DARK_GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setPadding(5);
        table.addCell(cell);
    }
    
    // Dados
    Font dataFont = new Font(Font.FontFamily.HELVETICA, 9);
    int colunaValorIndex = -1;
    for (int i = 0; i < colunas.length; i++) {
        if (colunas[i].contains("Valor")) {
            colunaValorIndex = i + 1;
            break;
        }
    }
    
    rs = stmt.executeQuery(sql); // Executa novamente para obter dados
    int rowsAdded = 0;
    
    while (rs.next() && rowsAdded < 100) {
        for (int i = 1; i <= colunas.length; i++) {
            String valor = rs.getString(i);
            if (valor == null) valor = "-";
            
            PdfPCell cell = new PdfPCell(new Phrase(valor, dataFont));
            cell.setPadding(4);
            
            // Somar valores se for coluna de valor
            if (i == colunaValorIndex && !valor.equals("-")) {
                try {
                    total += Double.parseDouble(valor);
                    cell.setBackgroundColor(BaseColor.LIGHT_GRAY);
                } catch (NumberFormatException e) {
                    // Ignora se não for número
                }
            }
            
            table.addCell(cell);
        }
        rowsAdded++;
    }
    
    // Adicionar linha de total
    if (rowsAdded > 0 && colunaValorIndex > 0) {
        PdfPCell totalLabel = new PdfPCell(new Phrase("TOTAL EM ABERTO:", 
            new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD)));
        totalLabel.setColspan(colunaValorIndex - 1);
        totalLabel.setHorizontalAlignment(Element.ALIGN_RIGHT);
        totalLabel.setPadding(5);
        table.addCell(totalLabel);
        
        PdfPCell totalCell = new PdfPCell(new Phrase(String.format("%,.2f Kz", total),
            new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.RED)));
        totalCell.setColspan(colunas.length - colunaValorIndex + 1);
        totalCell.setBackgroundColor(new BaseColor(255, 240, 240));
        totalCell.setHorizontalAlignment(Element.ALIGN_CENTER);
        totalCell.setPadding(5);
        table.addCell(totalCell);
    }
    
    rs.close();
    stmt.close();
    doc.add(table);
}

// Métodos auxiliares para cores
private BaseColor corPorEstado(String estado) {
    if (estado == null) return BaseColor.WHITE;
    switch(estado.toUpperCase()) {
        case "ATIVO": return new BaseColor(200, 255, 200);
        case "INATIVO": return new BaseColor(255, 200, 200);
        case "BLOQUEADO": return new BaseColor(255, 220, 150);
        default: return BaseColor.WHITE;
    }
}

private BaseColor corPorPerfil(String perfil) {
    if (perfil == null) return BaseColor.WHITE;
    switch(perfil.toUpperCase()) {
        case "ADMIN": return new BaseColor(255, 200, 200);
        case "BIBLIO": return new BaseColor(200, 255, 200);
        case "LEITOR": return new BaseColor(200, 200, 255);
        default: return BaseColor.WHITE;
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       gerarRelatorioPDFCompleto();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
