/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package template.main;

import classes.Utilizador;
import com.mycompany.library.sgbu;
import javax.swing.JOptionPane;
import template.main.containers.*;

/**
 *
 * @author naftalipinto
 */
public class layout extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    GutilizadorPanel user = new GutilizadorPanel();
    GeditoraPanel editora = new GeditoraPanel();
    GobraPanel obra = new GobraPanel();
    GcirculacaoPanel circulacao = new GcirculacaoPanel();
    GexemplarPanel exemplar = new GexemplarPanel();
 
    Utilizador usuario;
    public static Long idUser;
    public static String perfil;

    public layout(Utilizador u) {
        initComponents();
        setResizable(false);
        container.setLayout(null);
        this.usuario = u;
        idUser = u.getId();
        perfil = u.getPerfil();
        dashboard d = new dashboard();
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        d.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(d);
        container.revalidate();
        container.repaint();
        menuStarter();
    }

    private void menuStarter() {

        if (perfil.equals("ADMIN")) {
            mnEditora.setVisible(true);
            mnObra.setVisible(true);
            mnExemplar.setVisible(true);
            mnCirculacao.setVisible(true);
            mnUtilizador.setVisible(true);
            mnRelatorio.setVisible(true);
            mnPerfil.setVisible(true);
            return;
        }

        // BIBLIOTECÁRIO
        if (perfil.equals("BIBLIO")) {
            mnEditora.setVisible(true);
            mnObra.setVisible(true);
            mnExemplar.setVisible(true);
            mnCirculacao.setVisible(true);
            mnUtilizador.setVisible(true);
            mnRelatorio.setVisible(true);
            mnPerfil.setVisible(true);
        }

        // LEITOR
        if (perfil.equals("LEITOR")) {
            mnUtilizador.setVisible(false);
            mnObra.setVisible(false);
            mnExemplar.setVisible(false);
            mnRelatorio.setVisible(false);
            mnCirculacao.setVisible(true);
            mnEditora.setVisible(false);
            mnPerfil.setVisible(true);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mnUtilizador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mnObra = new javax.swing.JButton();
        mnExemplar = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        mnPerfil = new javax.swing.JButton();
        mnRelatorio = new javax.swing.JButton();
        mnCirculacao = new javax.swing.JButton();
        mnEditora = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1047, 707));

        container.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 695, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        mnUtilizador.setText("Gestão de utilizadores");
        mnUtilizador.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnUtilizador.addActionListener(this::mnUtilizadorActionPerformed);

        jButton2.setText("Inicio");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton2.addActionListener(this::jButton2ActionPerformed);

        mnObra.setText("Gestão de Obras");
        mnObra.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnObra.addActionListener(this::mnObraActionPerformed);

        mnExemplar.setText("Gestão de Exemplares");
        mnExemplar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnExemplar.addActionListener(this::mnExemplarActionPerformed);

        jButton6.setText("Terminar Sessão");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        mnPerfil.setText("Perfil");
        mnPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnPerfil.addActionListener(this::mnPerfilActionPerformed);

        mnRelatorio.setText("Relatórios");
        mnRelatorio.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnRelatorio.addActionListener(this::mnRelatorioActionPerformed);

        mnCirculacao.setText("Circulação");
        mnCirculacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnCirculacao.addActionListener(this::mnCirculacaoActionPerformed);

        mnEditora.setText("Gestão de Editoras");
        mnEditora.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        mnEditora.addActionListener(this::mnEditoraActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mnCirculacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnUtilizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnExemplar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mnObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButton6)
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(mnEditora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mnEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mnObra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mnExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mnUtilizador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnCirculacao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(mnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnUtilizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUtilizadorActionPerformed
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        user.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(user);
        container.revalidate();
        container.repaint();

    }//GEN-LAST:event_mnUtilizadorActionPerformed

    private void mnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnRelatorioActionPerformed

    private void mnCirculacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCirculacaoActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        circulacao.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(circulacao);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_mnCirculacaoActionPerformed

    private void mnEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEditoraActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        editora.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(editora);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_mnEditoraActionPerformed

    private void mnObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnObraActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        obra.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(obra);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_mnObraActionPerformed

    private void mnExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExemplarActionPerformed
        // TODO add your handling code here:
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        exemplar.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(exemplar);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_mnExemplarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja terminar a sessão? ") == 0) {
            this.dispose();
            new sgbu().setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void mnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPerfilActionPerformed
        // TODO add your handling code here:
        GperfilPanel perfil = new GperfilPanel(usuario);
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        perfil.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(perfil);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_mnPerfilActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dashboard d = new dashboard();
        container.removeAll();
        container.setLayout(null); // caso esteja usando layout absoluto
        d.setBounds(0, 0, container.getWidth(), container.getHeight());
        container.add(d);
        container.revalidate();
        container.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mnCirculacao;
    private javax.swing.JButton mnEditora;
    private javax.swing.JButton mnExemplar;
    private javax.swing.JButton mnObra;
    private javax.swing.JButton mnPerfil;
    private javax.swing.JButton mnRelatorio;
    private javax.swing.JButton mnUtilizador;
    // End of variables declaration//GEN-END:variables

}
